In [1]:
import numpy as np

**Задание 1**

In [2]:
N = int(input("Введите N"))

x = np.arange(0, N)
x = x[::-1]
x

Введите N5


array([4, 3, 2, 1, 0])

**Задание 2**

In [3]:
N = int(input("Введите N: "))

x = np.arange(0, N)

mtrx = np.diag(x[::-1], k=0)
print('\n', mtrx)

trace = mtrx.trace()
print('\n', "Trace of a matrix is:", trace)

Введите N: 5

 [[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]

 Trace of a matrix is: 10


**Задание 3**

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [8]:
left = np.array( [ [4,2,1], [1,3,0], [0,5,4] ] )
right = np.array([4,12,-3])

sol = np.linalg.solve(left, right)

print(f"x = {sol[0]}")
print(f"y = {sol[1]}")
print(f"z = {sol[2]}")

x = 0.4666666666666668
y = 3.844444444444444
z = -5.555555555555555
